# @Author: zhujinlong
# @Date:   2025-11-19 21:03:51
# @Last Modified by:   zhujinlong
# @Last Modified time: 2025-12-02 13:45:05
filebeat.inputs:
  # 采集系统日志（示例）
  - type: log
    id: gtcuser1  # 添加唯一标识符
    enabled: true
    paths:
      - /www/wwwroot/gtcuser_1/runtime/logs/debug-*.log
    fields:
      log_type: "debug"
      environment: "gtcuser1"
    fields_under_root: true
  - type: log
    id: gtcuser2  # 添加唯一标识符
    enabled: true
    paths:
      - /www/wwwroot/gtcuser_2/runtime/logs/debug-*.log
    fields:
      log_type: "debug"
      environment: "gtcuser2"
    fields_under_root: true

# 输出到 Kafka
output.kafka:
  # Kafka 集群地址（多个用逗号分隔，替换为实际地址）
  hosts: ["172.16.2.1:9092"]
  
  # Kafka 主题（可固定主题，或根据标签/日志源动态生成）
  topic: 'logs-gtcuser'  # 示例：按标签和日期分主题（如 logs-app）
  
  # 序列化格式（默认 JSON，可根据需求调整）
  codec.json:
    pretty: false  # 不格式化 JSON，节省空间
  
  # 若 Kafka 启用了认证（如 SASL/PLAIN），添加以下配置（可选）
  username: "Maxtech"                # 对应 KAFKA_CLIENT_USERS
  password: "Maxtechking520"         # 对应 KAFKA_CLIENT_PASSWORDS
  sasl.mechanism: PLAIN
  security.protocol: SASL_PLAINTEXT  # 与 KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP 中的 PLAINTEXT 对应